# Generated by Django 4.0.5 on 2022-06-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastrarPrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('genero', models.CharField(max_length=14, null=True)),
                ('cnpj', models.CharField(max_length=14, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('especialidade', models.CharField(default='Prestador', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Prestadores',
            },
        ),
    ]
