# Generated by Django 4.0.5 on 2022-06-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrarPrestador', '0002_especialidade_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Especialidade',
        ),
        migrations.AddField(
            model_name='cadastrarprestador',
            name='especialidade',
            field=models.CharField(default='Prestador', max_length=40, verbose_name='Especialidade'),
        ),
    ]
