# Generated by Django 4.0.5 on 2022-06-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrarPrestador', '0003_delete_especialidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastrarprestador',
            options={'verbose_name_plural': 'Prestadores de Serviços'},
        ),
        migrations.AlterField(
            model_name='cadastrarprestador',
            name='especialidade',
            field=models.CharField(default='Prestador', max_length=40),
        ),
        migrations.AlterField(
            model_name='cadastrarprestador',
            name='genero',
            field=models.CharField(choices=[('Feminino', 'F'), ('Masculino', 'M'), ('Outro', 'O')], max_length=14, null=True),
        ),
    ]
