# Generated by Django 4.0.5 on 2022-06-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrarPrestador', '0004_alter_cadastrarprestador_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrarprestador',
            name='genero',
            field=models.CharField(choices=[('1', 'Feminino'), ('2', 'Masculino'), ('3', 'Outro')], max_length=14, null=True),
        ),
    ]
