# Generated by Django 4.0.5 on 2022-06-22 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[['Feminino', 'F'], ['Masculino', 'M'], ['Outro', 'O']], max_length=14, null=True)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servicos.pessoa')),
                ('cnpj', models.CharField(max_length=14, null=True)),
                ('especialidade', models.CharField(choices=[('Encanador', 'Enc'), ('Motoboy', 'Mtb'), ('Designer', 'Dsg'), ('Eletricista', 'Eltr'), ('Salvador', 'Slv'), ('Motorista', 'Mtr'), ('Pintor', 'Ptr')], default='Prestador', max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Prestadores',
            },
            bases=('servicos.pessoa',),
        ),
    ]
