# Generated by Django 4.0.5 on 2022-06-22 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name_plural': 'Prestadores'},
        ),
    ]
