# Generated by Django 4.0.5 on 2022-06-22 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_alter_pessoa_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name_plural': 'Pessoas'},
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=12)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=6)),
                ('bairro', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=20)),
                ('complemento', models.CharField(max_length=120, null=True)),
                ('estado', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=8)),
                ('pessoa', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicos.pessoa')),
            ],
            options={
                'verbose_name': 'Endereço',
            },
        ),
    ]
