# Generated by Django 4.0.5 on 2022-06-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_alter_pessoa_options_telefone_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, null=True)),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Endereço',
            },
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={},
        ),
    ]
