# Generated by Django 4.0.5 on 2022-06-22 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicos', '0004_especialidade_alter_endereco_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servicos.pessoa')),
                ('cpf', models.CharField(max_length=11)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('servicos.pessoa',),
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, null=True)),
                ('prestacao', models.DateField(auto_now=True)),
                ('limite', models.DateField(auto_now=True)),
                ('descricao', models.TextField(null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicos.cliente')),
                ('prestador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicos.prestador')),
            ],
            options={
                'verbose_name': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localhost', models.CharField(max_length=50)),
                ('prestador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicos.prestador')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliar_servicos', models.IntegerField(default=0)),
                ('avaliar_prestador', models.IntegerField(default=0)),
                ('comentario', models.TextField(null=True)),
                ('data_hora', models.DateTimeField(null=True, verbose_name='Data da Avaliação')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicos.cliente')),
                ('servicos', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicos.servicos')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
    ]
